#!/usr/bin/env python3
"""Build transparent PNG assets for the current home-slider products.

The source catalog images are JPEGs with a white background. This script
removes only the near-white area connected to the image edge (it keeps white
parts that belong to the product itself) and writes the result to
public/slider-products. It also generates the TypeScript manifest consumed by
the carousel.
"""

from collections import deque
import json
from pathlib import Path
import sqlite3
import time
import urllib.request

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
DB_PATH = ROOT / "data" / "texnohouse.db"
OUTPUT_DIR = ROOT / "public" / "slider-products"
MANIFEST = ROOT / "src" / "lib" / "sliderImages.ts"
LIMIT = 60


def remove_edge_background(image: Image.Image) -> Image.Image:
    image = image.convert("RGBA")
    pixels = image.load()
    width, height = image.size
    visited: set[tuple[int, int]] = set()
    queue: deque[tuple[int, int]] = deque()

    # Seed a flood fill from the outside edge only. This avoids removing white
    # appliance details that are not connected to the image background.
    for x in range(width):
        queue.extend(((x, 0), (x, height - 1)))
    for y in range(height):
        queue.extend(((0, y), (width - 1, y)))

    def is_near_white(x: int, y: int) -> bool:
        red, green, blue, _ = pixels[x, y]
        return min(red, green, blue) >= 228 and max(red, green, blue) - min(red, green, blue) <= 28

    while queue:
        x, y = queue.popleft()
        if (x, y) in visited or not (0 <= x < width and 0 <= y < height):
            continue
        visited.add((x, y))
        if not is_near_white(x, y):
            continue

        red, green, blue, _ = pixels[x, y]
        # Soft edge against the product for a cleaner result on dark slides.
        alpha = max(0, min(255, int((245 - min(red, green, blue)) * 15)))
        pixels[x, y] = (red, green, blue, alpha)
        queue.extend(((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)))

    return image


def main() -> None:
    if not DB_PATH.exists():
        raise SystemExit(f"Missing database: {DB_PATH}")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(DB_PATH)
    rows = connection.execute(
        "SELECT id, images_json FROM products WHERE status = 'publish' ORDER BY id DESC LIMIT ?",
        (LIMIT,),
    ).fetchall()

    processed: list[int] = []
    for product_id, images_json in rows:
        images = json.loads(images_json)
        if not images or not images[0].get("src"):
            continue
        url = images[0]["src"]
        try:
            request = urllib.request.Request(url, headers={"User-Agent": "TexnoHouse image processor"})
            with urllib.request.urlopen(request, timeout=45) as response:
                source = Image.open(response).copy()
            target = OUTPUT_DIR / f"{product_id}.png"
            transparent = remove_edge_background(source)
            corners = (
                transparent.getpixel((0, 0))[3],
                transparent.getpixel((transparent.width - 1, 0))[3],
                transparent.getpixel((0, transparent.height - 1))[3],
                transparent.getpixel((transparent.width - 1, transparent.height - 1))[3],
            )
            # Full-bleed artwork cannot be presented as a transparent product
            # image. Exclude it from the slider rather than showing a rectangle.
            if max(corners) > 10:
                target.unlink(missing_ok=True)
                print(f"Skipped {product_id}: no removable outer background")
                continue
            transparent.save(target, "PNG", optimize=True)
            processed.append(product_id)
            print(f"Processed {product_id}")
        except Exception as error:
            print(f"Skipped {product_id}: {error}")
        time.sleep(0.08)

    manifest = (
        "// Generated by scripts/prepare_slider_images.py\n"
        f"export const SLIDER_TRANSPARENT_IMAGES = new Set<number>({processed!r});\n"
    )
    MANIFEST.write_text(manifest, encoding="utf-8")
    print(f"Wrote {len(processed)} transparent images and {MANIFEST}")


if __name__ == "__main__":
    main()
